package keywords

var Keywords = []string{
	"acl",
	"adventure",
	"room",
	"descriptions",
	"items",
	"connections",
	"connection",
	"item",
	"properties",
	"property",
	"verb",
	"synonym",
	"arguments",
	"arg",
	"placeholder",
	"description",
	"long_description",
	"code",
	"when",
	"say",
	"complete_fail",
	"remove_item",
	"give_item",
	"complete_success",
	"inital",
	"default",
}

var KeywordsToBinary = map[string]byte{
	"acl":              0x00,
	"adventure":        0x01,
	"room":             0x02,
	"descriptions":     0x03,
	"items":            0x04,
	"connections":      0x05,
	"connection":       0x06,
	"item":             0x07,
	"properties":       0x08,
	"property":         0x09,
	"verb":             0x0A,
	"synonym":          0x0B,
	"arguments":        0x0C,
	"arg":              0x0D,
	"placeholder":      0x0E,
	"description":      0x0F,
	"long_description": 0x10,
	"code":             0x11,
	"when":             0x12,
	"say":              0x13,
	"complete_fail":    0x14,
	"remove_item":      0x15,
	"give_item":        0x16,
	"complete_success": 0x17,
	"inital":           0x18,
	"default":          0x19,
}
